CREATE TABLE `bills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`billType` enum('electricity','gas') NOT NULL,
	`fileUrl` varchar(512),
	`fileKey` varchar(255),
	`fileName` varchar(255),
	`retailer` varchar(100),
	`billingPeriodStart` timestamp,
	`billingPeriodEnd` timestamp,
	`billingDays` int,
	`totalAmount` decimal(10,2),
	`dailySupplyCharge` decimal(8,4),
	`totalUsageKwh` decimal(10,2),
	`peakUsageKwh` decimal(10,2),
	`offPeakUsageKwh` decimal(10,2),
	`shoulderUsageKwh` decimal(10,2),
	`solarExportsKwh` decimal(10,2),
	`peakRateCents` decimal(8,4),
	`offPeakRateCents` decimal(8,4),
	`shoulderRateCents` decimal(8,4),
	`feedInTariffCents` decimal(8,4),
	`gasUsageMj` decimal(10,2),
	`gasRateCentsMj` decimal(8,4),
	`rawExtractedData` json,
	`extractionConfidence` decimal(5,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bills_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(50),
	`address` text NOT NULL,
	`state` varchar(10) NOT NULL,
	`hasGas` boolean DEFAULT false,
	`gasAppliances` json,
	`hasPool` boolean DEFAULT false,
	`poolVolume` int,
	`hasEV` boolean DEFAULT false,
	`evInterest` enum('none','interested','owns') DEFAULT 'none',
	`hasExistingSolar` boolean DEFAULT false,
	`existingSolarSize` decimal(5,2),
	`existingSolarAge` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255),
	`status` enum('draft','calculating','generated','exported','archived') NOT NULL DEFAULT 'draft',
	`proposalDate` timestamp NOT NULL DEFAULT (now()),
	`electricityBillId` int,
	`gasBillId` int,
	`calculations` json,
	`slidesData` json,
	`slideCount` int,
	`pdfUrl` varchar(512),
	`pptUrl` varchar(512),
	`lastExportedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stateRebates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`state` varchar(10) NOT NULL,
	`rebateType` enum('solar','battery','heat_pump_hw','heat_pump_ac','ev_charger','induction') NOT NULL,
	`name` varchar(255) NOT NULL,
	`amount` decimal(10,2),
	`isPercentage` boolean DEFAULT false,
	`maxAmount` decimal(10,2),
	`eligibilityCriteria` text,
	`incomeThreshold` decimal(12,2),
	`validFrom` timestamp,
	`validUntil` timestamp,
	`isActive` boolean DEFAULT true,
	`sourceUrl` varchar(512),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stateRebates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vppProviders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`programName` varchar(100),
	`availableStates` json,
	`hasGasBundle` boolean DEFAULT false,
	`dailyCredit` decimal(8,2),
	`eventPayment` decimal(8,2),
	`estimatedEventsPerYear` int,
	`bundleDiscount` decimal(8,2),
	`minBatterySize` decimal(5,2),
	`website` varchar(255),
	`notes` text,
	`isActive` boolean DEFAULT true,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vppProviders_id` PRIMARY KEY(`id`)
);
